services:
  - type: web
    name: my-flask-app # You can rename this to anything
    runtime: python
    buildCommand: ""
    startCommand: gunicorn main:app
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free
